# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a63cdc1885f4e1bf6e705dd314c4ae125c505aed9d1bf17c5fa56a9c014058ad59893f685a3a577a2112173bea581c85f57b3bd957253b04b5478ef58f45602

test:
  secret_key_base: 31c19879c7d977a18aa51ed496868be89f4ba3fbadd07fd2562af9dbfdfe360212663dd205e0ab8cd5c08542bd61ea0402f62ade67255cb955dd0e908953ae3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
